### ISSUE TITLE
Logs Functionality: Logs Controller

### ISSUE THREAD

**Issue by topboyasante** [OpenSource-GH/dumsor-tracker-api#10]
We need to implement the functionality for creating logs.

- Users can only create logs when they have logged in
- You don't need to log in to view logs created on the platform.

**Comment by starboyles** [comment]
@topboyasante assign please 😊

**Comment by lgyamfi** [comment]
> We need to implement the functionality for creating logs.
> 
> * Users can only create logs when they have logged in
> * You don't need to log in to view logs created on the platform.

@topboyasante assign please 😊

**Comment by topboyasante** [comment]
done sir
