### ISSUE TITLE
Remove outages field on user model

### ISSUE THREAD

**Issue by champ3oy** [OpenSource-GH/dumsor-tracker-api#13]
To avoid having to write the same data twice, we should remove the outages field on the user model and add the user's id to the log, with this, we can fetch logs for a user by matching the user id.

**Comment by topboyasante** [comment]
@starboyles thoughts?

**Comment by lgyamfi** [comment]
> @starboyles thoughts?

he's right

**Comment by topboyasante** [comment]
hi. is this task complete?

**Comment by champ3oy** [comment]
yes 👍🏻

**Comment by topboyasante** [comment]
okay. closing it then.
