### ISSUE TITLE
Error in userRoutes.js

### ISSUE THREAD

**Issue by meeklife** [OpenSource-GH/dumsor-tracker-api#15]
A wrong callBack function was called (getAllUsers)

**Comment by lgyamfi** [comment]
> A wrong callBack function was called (getAllUsers)
hi @meeklife 

please fix, create a branch, push, create PR

**Comment by meeklife** [comment]
> > A wrong callBack function was called (getAllUsers)
> > hi @meeklife
> 
> please fix, create a branch, push, create PR
Don't have permission

**Comment by lgyamfi** [comment]
> > > A wrong callBack function was called (getAllUsers)
> > > hi @meeklife
> > 
> > 
> > please fix, create a branch, push, create PR
> > Don't have permission

wow permission to?

**Comment by meeklife** [comment]
> > > > A wrong callBack function was called (getAllUsers)
> > > > hi @meeklife
> > > 
> > > 
> > > please fix, create a branch, push, create PR
> > > Don't have permission
> 
> wow permission to?

Am not a contributor yet 
Don't worry, I forked it
