### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by champ3oy** [OpenSource-GH/dumsor-tracker-api#6]
How do we know what is being worked on and what features are currently left? I suggest we have a board or raise new features as issues.

**Comment by kurtiz** [comment]
yhyh... kinda lost here

**Comment by topboyasante** [comment]
Kindly check the progress tab.
@champ3oy @kurtiz

**Comment by kurtiz** [comment]
Progress Tab?

**Comment by topboyasante** [comment]
https://github.com/orgs/OpenSource-GH/projects/1
Issues have been created, kindly check them out.

**Comment by kurtiz** [comment]
ok sure

**Comment by kurtiz** [comment]
![image](https://github.com/OpenSource-GH/dumsor-tracker-api/assets/61732071/eed52dc2-2905-4e6d-b74a-7a7705ede4ed)
this is what i got... maybe the project is private so i can't access it

**Comment by topboyasante** [comment]
please try again

**Comment by kurtiz** [comment]
alright sure

**Comment by kurtiz** [comment]
ok seen... so do i create a task then follow through, or i wait for a task to be added to the todo where i can try to participate

**Comment by topboyasante** [comment]
issues have been created on the issues tab, you can pick one and work on.
https://github.com/OpenSource-GH/dumsor-tracker-api/issues

**Comment by kurtiz** [comment]
noted

**Comment by starboyles** [comment]
okay
