### ISSUE TITLE
Authentication : User Controller

### ISSUE THREAD

**Issue by topboyasante** [OpenSource-GH/dumsor-tracker-api#8]
We want users to authenticate using two methods:
- Sign in and register with email and password
- Sign in and register with phone number and OTP

This task requires that you create a user controller to do the following:
- Create functionality for users to sign in and sign up
- Create functionality for users to recover their account (Forgot Password)

**Comment by greatdaveo** [comment]
> We want users to authenticate using two methods:
> 
> * Sign in and register with email and password
> * Sign in and register with phone number and OTP
> 
> This task requires that you create a user controller to do the following:
> 
> * Create functionality for users to sign in and sign up
> * Create functionality for users to recover their account (Forgot Password)

Hi chief! I would love to give this a shot! 😁🤝

**Comment by topboyasante** [comment]
sure! assigning this to you

**Comment by topboyasante** [comment]
@greatdaveo please is this task complete?

**Comment by greatdaveo** [comment]
> @greatdaveo please is this task complete?

@topboyasante Hello, I previously used MongoDB, and I was told last night that the team intends to switch to PostgreSQL, and I am working on refactoring the code to that.
