### ISSUE TITLE
Logs Functionality: Log Model

### ISSUE THREAD

**Issue by topboyasante** [OpenSource-GH/dumsor-tracker-api#9]
This task requires that you create the log model.
The Model should be as follows:
- a foreign key to link a log to the user who created it
- the location the log was recorded
- The time the lights went out
- The time the lights came back

**Comment by lgyamfi** [comment]
> This task requires that you create the log model. The Model should be as follows:
> 
> * a foreign key to link a log to the user who created it
> * the location the log was recorded
> * The time the lights went out
> * The time the lights came back

Assign this to me Kwasi

**Comment by lgyamfi** [comment]
done
